// <auto-generated />
using System;
using DotaParser.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotaParser.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotaParser.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageRank")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<long>("DotaMatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("LeaverStatus")
                        .HasColumnType("integer");

                    b.Property<int>("LobbyType")
                        .HasColumnType("integer");

                    b.Property<int?>("PartySize")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerSlot")
                        .HasColumnType("integer");

                    b.Property<bool>("RadiantWin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DotaMatchId");

                    b.HasIndex("PlayerAccountId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DotaParser.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsDotaPlus")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeaderboardRank")
                        .HasColumnType("integer");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RankTier")
                        .HasColumnType("integer");

                    b.Property<long>("SteamAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SteamAccountId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DotaParser.Domain.Entities.Match", b =>
                {
                    b.HasOne("DotaParser.Domain.Entities.Player", "Player")
                        .WithMany("Matches")
                        .HasForeignKey("PlayerAccountId")
                        .HasPrincipalKey("SteamAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DotaParser.Domain.Entities.Player", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
